// src/widgets/stock-chart/ui/StockChart.vue
<script setup lang="ts">
import {computed} from 'vue';
import {format} from 'date-fns';
import {ru} from 'date-fns/locale';

import {Card, CardContent, CardHeader, Badge} from '@/shared/ui';
import {useStockHistory} from '@/entities/price-history';
import {useUIStore, storeToRefs} from '@/shared/store';
import type {Timeframe, PricePoint} from '@/shared/api';

const TIMEFRAMES: Timeframe[] = ['1D', '1W', '1M', '1Y'];

function formatXAxisTimestamp(ts: number, timeframe: Timeframe): string {
  const date = new Date(ts);
  switch (timeframe) {
    case '1D':
      return format(date, 'HH:mm');
    case '1W':
      return format(date, 'eeee', {locale: ru});
    case '1M':
      return format(date, 'dd.MM');
    case '1Y':
      return format(date, 'LLL', {locale: ru});
    default:
      return format(date, 'd MMM', {locale: ru});
  }
}

function formatTooltipTimestamp(timestamp: Date): string {
  return format(timestamp, 'd MMM, HH:mm', {locale: ru});
}

interface ChartDataPoint {
  x: number;
  y: number;
  timestamp: Date;
}

function prepareChartData(points: PricePoint[]): ChartDataPoint[] {
  return points.map(p => ({
    x: p.timestamp.getTime(),
    y: p.price,
    timestamp: p.timestamp,
  }));
}

const uiStore = useUIStore();
const {selectedTicker, chartTimeframe} = storeToRefs(uiStore);

const {data, isLoading} = useStockHistory(selectedTicker, chartTimeframe);

const preparedData = computed(() => prepareChartData(data.value ?? []));

const latestPrice = computed(() => data.value?.[data.value.length - 1]?.price);
const previousPrice = computed(
  () => data.value?.[data.value.length - 2]?.price,
);
const priceChange = computed(() => {
  if (latestPrice.value !== undefined && previousPrice.value !== undefined) {
    return (
      ((latestPrice.value - previousPrice.value) / previousPrice.value) * 100
    );
  }
  return 0;
});

const chartOptions = computed(() => ({
  chart: {
    type: 'area',
    animations: {enabled: false},
    toolbar: {show: false},
    zoom: {enabled: false},
  },
  stroke: {
    curve: 'monotone' as const,
    width: 2,
  },
  fill: {
    type: 'gradient',
    gradient: {
      shadeIntensity: 1,
      opacityFrom: 0.3,
      opacityTo: 0,
      stops: [0, 100],
    },
  },
  xaxis: {
    type: 'datetime' as const,
    labels: {
      formatter: (value: number) =>
        formatXAxisTimestamp(value, chartTimeframe.value),
      style: {fontSize: '12px'},
    },
    axisBorder: {show: false},
    axisTicks: {show: false},
  },
  yaxis: {
    labels: {
      formatter: (value: number) => `$${value.toFixed(0)}`,
      style: {fontSize: '12px'},
    },
  },
  grid: {
    borderColor: '#e5e7eb',
    strokeDashArray: 3,
  },
  tooltip: {
    custom: ({dataPointIndex}: {dataPointIndex: number}) => {
      const point = preparedData.value[dataPointIndex];
      if (!point) return '';
      return `
        <div class="rounded-lg border bg-white p-2 shadow-sm">
          <div class="text-xs text-gray-500">${formatTooltipTimestamp(point.timestamp)}</div>
          <div class="font-mono font-semibold">${point.y.toLocaleString('ru-RU', {style: 'currency', currency: 'USD'})}</div>
        </div>
      `;
    },
  },
}));

const series = computed(() => [
  {
    name: 'Цена',
    data: preparedData.value,
  },
]);

function handleTimeframeChange(timeframe: Timeframe) {
  uiStore.setChartTimeframe(timeframe);
}
</script>

<template>
  <Card v-if="!selectedTicker">
    <CardHeader>
      <div class="text-lg font-semibold">График акции</div>
    </CardHeader>
    <CardContent
      class="flex h-80 items-center justify-center text-muted-foreground"
    >
      Выберите акцию в таблице для отображения графика
    </CardContent>
  </Card>

  <Card v-else-if="isLoading">
    <CardHeader>
      <div class="text-lg font-semibold">{{ selectedTicker }}</div>
    </CardHeader>
    <CardContent
      class="flex h-80 items-center justify-center text-muted-foreground"
    >
      Загрузка данных...
    </CardContent>
  </Card>

  <Card v-else-if="!data || data.length === 0">
    <CardHeader>
      <div class="text-lg font-semibold">{{ selectedTicker }}</div>
    </CardHeader>
    <CardContent
      class="flex h-80 items-center justify-center text-muted-foreground"
    >
      Нет данных для отображения
    </CardContent>
  </Card>

  <Card v-else>
    <CardHeader>
      <div class="flex items-center justify-between">
        <div class="text-lg font-semibold">
          {{ selectedTicker }}
          <span
            v-if="latestPrice !== undefined"
            class="ml-4 text-base font-normal text-muted-foreground"
          >
            {{
              latestPrice.toLocaleString('ru-RU', {
                style: 'currency',
                currency: 'USD',
              })
            }}
            <span
              :class="[
                'ml-2',
                priceChange >= 0 ? 'text-green-600' : 'text-red-600',
              ]"
            >
              {{ priceChange >= 0 ? '+' : '' }}{{ priceChange.toFixed(2) }}%
            </span>
          </span>
        </div>
        <div class="flex gap-2">
          <Badge
            v-for="tf in TIMEFRAMES"
            :key="tf"
            :variant="chartTimeframe === tf ? 'default' : 'outline'"
            class="cursor-pointer"
            @click="handleTimeframeChange(tf)"
          >
            {{ tf }}
          </Badge>
        </div>
      </div>
    </CardHeader>
    <CardContent>
      <div class="h-80" data-testid="stock-chart-container">
        <apexchart
          type="area"
          :options="chartOptions"
          :series="series"
          height="320"
        />
      </div>
    </CardContent>
  </Card>
</template>

// src/widgets/stock-chart/ui/StockChart.tsx
import {Card, CardContent, CardHeader, CardTitle} from '@/shared/ui/card';
import {Badge} from '@/shared/ui/badge';
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from 'recharts';
import {format} from 'date-fns';

import {useStockHistory} from '@/entities/price-history';
import {useUIStore} from '@/shared/store';
import type {Timeframe, PricePoint} from '@/shared/api';
import {useMemo} from 'react';

const TIMEFRAMES: Timeframe[] = ['1D', '1W', '1M', '1Y'];

function formatXAxisTimestamp(ts: number, timeframe: Timeframe): string {
  const date = new Date(ts);
  switch (timeframe) {
    case '1D':
      return format(date, 'HH:mm');
    case '1W':
      return format(date, 'eeee');
    case '1M':
      return format(date, 'dd.MM');
    case '1Y':
      return format(date, 'LLL');
    default:
      return format(date, 'd MMM');
  }
}

function formatTooltipTimestamp(timestamp: Date): string {
  return format(timestamp, 'd MMM, HH:mm');
}

interface ChartDataPoint {
  ts: number;
  timestamp: Date;
  price: number;
}

function prepareChartData(points: PricePoint[]): ChartDataPoint[] {
  return points.map(p => {
    return {
      ts: p.timestamp.getTime(),
      timestamp: p.timestamp,
      price: p.price,
    };
  });
}

interface TimeframeSelectorProps {
  value: Timeframe;
  onChange: (timeframe: Timeframe) => void;
}

export function TimeframeSelector({value, onChange}: TimeframeSelectorProps) {
  return (
    <div className="flex gap-2">
      {TIMEFRAMES.map(tf => (
        <Badge
          key={tf}
          variant={value === tf ? 'default' : 'outline'}
          className="cursor-pointer"
          onClick={() => onChange(tf)}
        >
          {tf}
        </Badge>
      ))}
    </div>
  );
}

interface StockChartHeaderProps {
  ticker: string | null;
  timeframe: Timeframe;
  onTimeframeChange: (timeframe: Timeframe) => void;
  latestPrice: number | undefined;
  priceChange: number;
}

function StockChartHeader({
  ticker,
  timeframe,
  onTimeframeChange,
  latestPrice,
  priceChange,
}: StockChartHeaderProps) {
  return (
    <div className="flex items-center justify-between">
      <CardTitle>
        {ticker ? `${ticker}` : 'Выберите акцию'}
        {latestPrice !== undefined && (
          <span className="ml-4 text-lg font-normal text-muted-foreground">
            {latestPrice.toLocaleString('ru-RU', {
              style: 'currency',
              currency: 'USD',
            })}
            <span
              className={`
                ml-2
                ${priceChange >= 0 ? 'text-green-600' : 'text-red-600'}
              `}
            >
              {priceChange >= 0 ? '+' : ''}
              {priceChange.toFixed(2)}%
            </span>
          </span>
        )}
      </CardTitle>
      {ticker && (
        <TimeframeSelector value={timeframe} onChange={onTimeframeChange} />
      )}
    </div>
  );
}

export function StockChart() {
  const selectedTicker = useUIStore(s => s.selectedTicker);
  const chartTimeframe = useUIStore(s => s.chartTimeframe);
  const setChartTimeframe = useUIStore(s => s.setChartTimeframe);

  const {data, isLoading} = useStockHistory(selectedTicker, chartTimeframe);

  const preparedData = useMemo(() => {
    return prepareChartData(data ?? []);
  }, [data]);

  const latestPrice = data?.[data.length - 1]?.price;
  const previousPrice = data?.[data.length - 2]?.price;
  const priceChange =
    latestPrice !== undefined && previousPrice !== undefined
      ? ((latestPrice - previousPrice) / previousPrice) * 100
      : 0;

  if (!selectedTicker) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>График акции</CardTitle>
        </CardHeader>
        <CardContent
          className="
            flex h-80 items-center justify-center text-muted-foreground
          "
        >
          Выберите акцию в таблице для отображения графика
        </CardContent>
      </Card>
    );
  }

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>{selectedTicker}</CardTitle>
        </CardHeader>
        <CardContent
          className="
            flex h-80 items-center justify-center text-muted-foreground
          "
        >
          Загрузка данных...
        </CardContent>
      </Card>
    );
  }

  if (!data || data.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>{selectedTicker}</CardTitle>
        </CardHeader>
        <CardContent
          className="
            flex h-80 items-center justify-center text-muted-foreground
          "
        >
          Нет данных для отображения
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <StockChartHeader
          ticker={selectedTicker}
          timeframe={chartTimeframe}
          onTimeframeChange={setChartTimeframe}
          latestPrice={latestPrice}
          priceChange={priceChange}
        />
      </CardHeader>
      <CardContent>
        <div className="h-80" data-testid="stock-chart-container">
          <ResponsiveContainer width="100%" height={400}>
            <AreaChart data={preparedData}>
              <defs>
                <linearGradient id="colorPrice" x1="0" y1="0" x2="0" y2="1">
                  <stop
                    offset="5%"
                    stopColor="hsl(var(--primary))"
                    stopOpacity={0.3}
                  />
                  <stop
                    offset="95%"
                    stopColor="hsl(var(--primary))"
                    stopOpacity={0}
                  />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
              <XAxis
                dataKey="ts"
                type="number"
                scale="time"
                domain={['dataMin', 'dataMax']}
                tickFormatter={(ts: number) =>
                  formatXAxisTimestamp(ts, chartTimeframe)
                }
                tick={{fontSize: 12}}
                tickLine={false}
                axisLine={false}
                className="text-muted-foreground"
                interval="preserveStartEnd"
              />
              <YAxis
                domain={['auto', 'auto']}
                tick={{fontSize: 12}}
                tickLine={false}
                axisLine={false}
                tickFormatter={(v: number) => `$${v.toFixed(0)}`}
                className="text-muted-foreground"
              />
              <Tooltip
                content={({active, payload}) => {
                  if (!active || !payload?.length) return null;
                  const point = payload[0].payload as ChartDataPoint;
                  return (
                    <div className="rounded-lg border bg-background p-2 shadow-sm">
                      <div className="text-xs text-muted-foreground">
                        {formatTooltipTimestamp(point.timestamp)}
                      </div>
                      <div className="font-mono font-semibold">
                        {point.price.toLocaleString('ru-RU', {
                          style: 'currency',
                          currency: 'USD',
                        })}
                      </div>
                    </div>
                  );
                }}
              />
              <Area
                type="monotone"
                dataKey="price"
                stroke="hsl(var(--primary))"
                strokeWidth={2}
                fill="url(#colorPrice)"
                isAnimationActive={false}
              />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </CardContent>
    </Card>
  );
}
