// src/widgets/stock-table/ui/StockTable.vue
<script setup lang="ts">
import {computed} from 'vue';

import {Card, CardContent, CardHeader, CardTitle, Badge} from '@/shared/ui';
import {useStocks} from '@/entities/stock';
import {useUIStore, storeToRefs} from '@/shared/store';
import {SearchInput} from '@/features/search';
import {SECTORS} from '@/shared/api';

import StockTableBody from './StockTableBody.vue';

const uiStore = useUIStore();
const {selectedTicker, sectorFilter, searchQuery} = storeToRefs(uiStore);

const {data, isLoading, fetchNextPage, hasNextPage, isFetchingNextPage} =
  useStocks({
    sector: sectorFilter,
    search: searchQuery,
  });

const stocks = computed(() => {
  if (!data.value) return [];
  return data.value.pages.flatMap(page => page.stocks);
});

const queryKey = computed(
  () => `${sectorFilter.value ?? 'all'}-${searchQuery.value ?? ''}`,
);

function handleSelect(ticker: string) {
  uiStore.setSelectedTicker(ticker);
}

function handleBuy(ticker: string) {
  uiStore.openTradeModal(ticker, 'buy');
}

function handleSell(ticker: string) {
  uiStore.openTradeModal(ticker, 'sell');
}

function handleSectorClick(sector: string | null) {
  uiStore.setSectorFilter(sector);
}

async function handleLoadMore() {
  await fetchNextPage();
}
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Акции</CardTitle>
    </CardHeader>
    <CardContent class="flex flex-col gap-4">
      <div class="flex flex-col gap-3">
        <SearchInput />
        <div class="flex flex-wrap gap-2">
          <Badge
            :variant="sectorFilter === null ? 'default' : 'outline'"
            class="cursor-pointer"
            @click="handleSectorClick(null)"
          >
            Все
          </Badge>
          <Badge
            v-for="sector in SECTORS"
            :key="sector"
            :variant="sectorFilter === sector ? 'default' : 'outline'"
            class="cursor-pointer"
            @click="handleSectorClick(sector)"
          >
            {{ sector }}
          </Badge>
        </div>
      </div>
      <div
        class="flex items-center border-b border-gray-200 px-4 py-2 text-sm font-medium text-muted-foreground"
      >
        <div class="min-w-12">Тикер</div>
        <div class="min-w-32">Название</div>
        <div class="w-32 text-right">Цена</div>
        <div class="w-24 text-right">24ч</div>
        <div class="w-24 text-right">В портфеле</div>
        <div class="w-48 text-right">Действия</div>
      </div>
      <StockTableBody
        :stocks="stocks"
        :selected-ticker="selectedTicker"
        :is-loading="isLoading"
        :query-key="queryKey"
        @select="handleSelect"
        @buy="handleBuy"
        @sell="handleSell"
      />
      <button
        v-if="hasNextPage"
        type="button"
        :disabled="isFetchingNextPage"
        class="mt-2 rounded-sm bg-primary px-4 py-2 text-primary-foreground disabled:opacity-50"
        @click="handleLoadMore"
      >
        {{ isFetchingNextPage ? 'Загрузка...' : 'Загрузить ещё' }}
      </button>
    </CardContent>
  </Card>
</template>

// src/widgets/stock-table/ui/StockTable.tsx
import {Card, CardContent, CardHeader, CardTitle} from '@/components/ui/card';
import {useStocks} from '@/entities/stock';
import {useUIStore} from '@/shared/store';
import {usePriceFeed, type Stock} from '@/shared/api';

import {TableFilters} from './TableFilters';
import {StockTableBody} from './StockTableBody';
import {useCallback, useMemo} from 'react';

function flattenStocks(data: ReturnType<typeof useStocks>['data']): Stock[] {
  if (!data) return [];
  return data.pages.flatMap(page => page.stocks);
}

export function StockTable() {
  const selectedTicker = useUIStore(s => s.selectedTicker);
  const setSelectedTicker = useUIStore(s => s.setSelectedTicker);
  const sectorFilter = useUIStore(s => s.sectorFilter);
  const searchQuery = useUIStore(s => s.searchQuery);
  const setSectorFilter = useUIStore(s => s.setSectorFilter);
  const setSearchQuery = useUIStore(s => s.setSearchQuery);
  const openTradeModal = useUIStore(s => s.openTradeModal);

  const {data, isLoading, fetchNextPage, hasNextPage, isFetchingNextPage} =
    useStocks({
      sector: sectorFilter ?? undefined,
      search: searchQuery || undefined,
    });

  usePriceFeed({
    sector: sectorFilter ?? undefined,
    search: searchQuery || undefined,
  });

  const stocks = useMemo(() => flattenStocks(data), [data]);

  const queryKey = useMemo(
    () => `${sectorFilter ?? 'all'}-${searchQuery ?? ''}`,
    [sectorFilter, searchQuery],
  );

  const handleSelect = useCallback(
    (ticker: string) => {
      setSelectedTicker(ticker);
    },
    [setSelectedTicker],
  );

  const handleBuy = useCallback(
    (ticker: string) => {
      openTradeModal(ticker, 'buy');
    },
    [openTradeModal],
  );

  const handleSell = useCallback(
    (ticker: string) => {
      openTradeModal(ticker, 'sell');
    },
    [openTradeModal],
  );

  return (
    <Card>
      <CardHeader>
        <CardTitle>Акции</CardTitle>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <TableFilters
          sectorFilter={sectorFilter}
          searchQuery={searchQuery}
          onSectorChange={setSectorFilter}
          onSearchChange={setSearchQuery}
        />
        <div
          className="
            flex items-center border-b border-gray-200 px-4 py-2 text-sm
            font-medium text-muted-foreground
          "
        >
          <div className="w-24">Тикер</div>
          <div className="flex-1">Название</div>
          <div className="w-32 text-right">Цена</div>
          <div className="w-24 text-right">24ч</div>
          <div className="w-24 text-right">В портфеле</div>
          <div className="w-32 text-right">Действия</div>
        </div>
        <StockTableBody
          stocks={stocks}
          selectedTicker={selectedTicker}
          onSelect={handleSelect}
          onBuy={handleBuy}
          onSell={handleSell}
          isLoading={isLoading}
          queryKey={queryKey}
        />
        {hasNextPage && (
          <button
            type="button"
            onClick={() => void fetchNextPage()}
            disabled={isFetchingNextPage}
            className="
              mt-2 rounded-sm bg-primary px-4 py-2 text-primary-foreground
              disabled:opacity-50
            "
          >
            {isFetchingNextPage ? 'Загрузка...' : 'Загрузить ещё'}
          </button>
        )}
      </CardContent>
    </Card>
  );
}
